"""Core policies for the Mini Hivo coding orchestrator.

The executable remains ``mini.py`` for backwards compatibility.  This package
contains policy and state-free components that can be tested without Ollama or
a browser.
"""

from .model_policy import GEMMA_MODEL, SingleModelPolicy
from .memory import MemoryStore
from .playbooks import build_execution_stages, classify_project
from .projects import ProjectStore
from .project_brain_refs import (
    ProjectBrainEntity, TypedReference, create_project_brain_entity,
    mark_reference_stale, normalize_legacy_brain_record,
)
from .repository_map import RepositoryMap, build_repository_map, incremental_reindex
from .project_world_model import ProjectWorldFact, ProjectWorldModel
from .semantic_coupling import (
    SEMANTIC_COUPLING_SCHEMA_VERSION,
    SHARED_CONTRACT, SHARED_STATE_TRANSITION, SHARED_INVARIANT,
    PRODUCER_CONSUMER, TYPE_SCHEMA_COUPLING, PUBLIC_SURFACE_COUPLING,
    ORDER_DEPENDENT, VERIFICATION_COUPLING, CONFIGURATION_COUPLING,
    INDEPENDENT, GROUP, MERGE_REQUIRED, BLOCKED,
    ANALYSIS_VALIDATED, ANALYSIS_PARTIAL, ANALYSIS_CONFLICTING,
    AUTHORITY_RANKING,
    SemanticCoupling, SemanticWorkGroup, SemanticCouplingAnalyzer,
    analyze_semantic_coupling, refine_semantic_decomposition,
    verify_semantic_group, benchmark_semantic_coupling_scenarios,
)
from .pre_mutation_impact import (
    PRE_MUTATION_IMPACT_SCHEMA_VERSION,
    DIRECT_IMPLEMENTATION, PUBLIC_CONTRACT, CALLER_CONSUMER, TYPE_SCHEMA,
    STATE_TRANSITION, EXPORT_PUBLIC_SURFACE, TEST_BEHAVIOR, CONFIGURATION,
    INVARIANT, DEPENDENCY, SIDE_EFFECT, IMPACT_CATEGORIES,
    EXPECTED_AND_OBSERVED, EXPECTED_BUT_MISSING, UNEXPECTED_BUT_RELATED,
    UNEXPECTED_AND_OUT_OF_SCOPE, PRESERVATION_VIOLATED, UNRESOLVED,
    CONFLICTING, IMPACT_ACCEPTED, IMPACT_INCOMPLETE, IMPACT_CONFLICT,
    IMPACT_REQUIRED, IMPACT_INVALID, IMPACT_STALE, IMPACT_VERIFICATION_FAILED,
    IMPACT_REPLAN_REQUIRED, IMPACT_PASSED, IMPACT_FAILED,
    PreMutationImpactContract, ImpactContract, ImpactComparison,
    MAX_IMPACT_TARGETS, MAX_IMPACT_OBLIGATIONS, MAX_IMPACT_PRESERVATIONS,
    MAX_EXPECTED_RELATION_DELTAS, MAX_IMPACT_EVIDENCE_ITEMS,
    MAX_IMPACT_ACTUAL_TARGETS, MAX_IMPACT_CHANGED_PATHS, MAX_IMPACT_REVISIONS,
    MAX_IMPACT_CONTRACT_REVISIONS, MAX_PRESERVATIONS,
    MAX_IMPACT_NEIGHBORHOOD_FACTS,
    SATISFIED, FAILED, NOT_APPLICABLE,
    MAX_IMPACT_PROJECTION_CHARS,
    build_pre_mutation_impact_contract, create_pre_mutation_impact_contract,
    build_impact_contract, validate_pre_mutation_impact_contract,
    validate_impact_contract, accept_pre_mutation_impact_contract,
    accept_impact_contract, impact_mutation_block_reason,
    mutation_authorization_block_reason, capture_actual_mutation_impact,
    capture_mutation_impact,
    evaluate_verification_obligations, compare_pre_mutation_impact,
    compare_impact_contract, verify_pre_mutation_impact,
    revise_pre_mutation_impact_contract, revise_impact_contract,
    project_impact_contract, impact_contract_projection,
    benchmark_impact_contract_scenarios, benchmark_pre_mutation_impact,
)
from .reference_resolution import (
    EvidenceResolutionRequest, ProjectReferenceResolver, ResolvedEvidence,
)
from .lexical_index import (
    LexicalIndex, build_lexical_index, incremental_lexical_update,
)
from .task_working_set import (
    TaskWorkingSet, WorkingSetBudget, WorkingSetItem, build_task_working_set,
    expand_working_set,
)
from .repo_intelligence import (
    RepoIntelligenceQuery, SearchCandidate, RepoIntelligenceResult,
    RepoIntelligenceBudget, search_repository, benchmark_repository_navigation,
    SearchIntent, classify_search_intents, extract_query_signals,
)
from .diagnostic_hypotheses import (
    DiagnosticBudget, DiagnosticFailureEvidence, DiagnosticHypothesis,
    DiagnosticSession, seed_hypotheses,
)
from .experiment_selector import DiagnosticExperiment, ExperimentSelector, SelectionDecision
from .experiment_sandbox import (
    CounterfactualMutationSpec, ExperimentalSandbox, ProbePermission,
    classify_probe_permission, canonical_subject_hash, subject_tree_snapshot,
)
from .experimental_evidence import (
    BaselineReceipt, DiagnosticResult, EvidenceItem, ExperimentReceipt,
    ExperimentalEvidenceEngine, ExperimentalEvidenceLedger, VerificationResult,
    generate_test_failure_experiments, generate_error_location_experiments,
    generate_dependency_stub_experiment, generate_input_perturbation_experiment,
    session_from_recovery_failure, benchmark_diagnostic_scenarios,
)
from .coverage_evidence import (
    CoverageEvidence, CoverageEvidenceProvider, COVERAGE_AVAILABLE,
    COVERAGE_NOT_AVAILABLE, COVERAGE_STALE, collect_coverage_evidence,
    ochiai_suspiciousness,
)
from .fault_localization import (
    FaultFailureEvidence, FailureEvidence, LocalizationBudget,
    FaultLocalizationBudget, FaultLocalizationRequest, StackFrame, StackTraceParser,
    FaultCandidate, FaultLocalizationResult, FaultLocalizationEngine,
    parse_stack_trace, parse_stack_frames, build_fault_localization_request,
    localize_fault, seed_hypotheses_from_localization,
    rerank_with_experimental_evidence, benchmark_fault_localization_scenarios,
    benchmark_fault_localization, TEST_FAILURE, ASSERTION_FAILURE,
    RUNTIME_EXCEPTION, SYNTAX_FAILURE, VERIFICATION_FAILURE, ORACLE_FAILURE,
    WORKER_EXECUTION_FAILURE, INTEGRATION_FAILURE, ERROR_LOCATION_SIGNAL,
    STACK_TRACE_SIGNAL, FAILING_TEST_SIGNAL, TEST_DEPENDENCY_SIGNAL,
    COVERAGE_SIGNAL, GRAPH_PROXIMITY_SIGNAL, CHANGE_PROXIMITY_SIGNAL,
    LEXICAL_SIGNAL, BRAIN_CONTRACT_SIGNAL, EXPERIMENTAL_EVIDENCE_SIGNAL,
    LOW, MEDIUM, HIGH, VERY_HIGH, DNT_PROTECTED,
)
from .repair_problem import (
    CORE5_SCHEMA_VERSION, DIAGNOSTIC_SUSPECT, FINAL_MUTATION_AUTHORIZED,
    READ_ONLY_SUPPORT as CORE5_READ_ONLY_SUPPORT, DNT_PROTECTED as CORE5_DNT_PROTECTED,
    PatchSearchBudget, CandidateSearchBudget, RepairTargetSet, RepairEvidencePacket,
    RepairProblem,
)
from .mutation_strategy import (
    EXACT_VALUE_CHANGE, CONDITION_CHANGE, EXPORT_IMPORT_REPAIR,
    FUNCTION_LOCAL_REWRITE, SMALL_INSERTION, SMALL_DELETION, CALLSITE_ADJUSTMENT,
    DEPENDENCY_CONFIGURATION_CHANGE, MULTI_LOCATION_SINGLE_FILE_CHANGE,
    MULTI_FILE_BOUNDED_CHANGE, UNKNOWN_STRUCTURAL_CHANGE, STRATEGY_CLASSES,
    StrategyDecision, MutationStrategyRouter, route_mutation_strategies,
)
from .patch_candidates import (
    DETERMINISTIC_OPERATOR, REPAIR_TEMPLATE, EXPERIMENT_DERIVED, MODEL_PROPOSED,
    USER_PROPOSED, PROPOSED, STALE_BASE, AUTHORITY_BLOCKED, SYNTAX_INVALID,
    TARGET_FAILED, GUARD_REGRESSION, REGRESSION_RISK, CONTRACT_CONFLICT, V25_5_REJECTED,
    V25_6_FAILED, VIABLE, VERIFIED, PatchOperation, PatchRepresentation,
    STALE_PATCH_BASE, SYNTAX_INVALID_CANDIDATE, PatchCandidate, PatchCandidateReceipt, CandidateFailureEvidence,
    ModelPatchCandidateProvider, generate_deterministic_candidates,
    generate_experiment_derived_candidate, normalize_model_candidates, generate_patch_candidates,
)
from .patch_search import (
    PatchSearchResult, PatchSearchEngine, search_patch_candidates,
    apply_selected_patch_candidate, update_repository_indexes_after_application,
    benchmark_patch_search_scenarios, VERIFIED_CANDIDATE, BEST_VIABLE_CANDIDATE,
    APPLY_SELECTED_CANDIDATE, NO_VIABLE_PATCH_CANDIDATE, PATCH_SEARCH_BUDGET_REACHED,
)
from .project_blueprint import (
    CORE6_BLUEPRINT_SCHEMA_VERSION, REQUIREMENT_CATEGORIES, ARCHITECTURE_STYLES,
    CONTRACT_STATUSES, ProjectRequirement, InterfaceSchema, ProjectInterface,
    DataSchema, ContractSchema, ModuleContract, ProjectBlueprint,
    blueprint_identity, contract_identity, schema_identity,
)
from .generation_dag import (
    DEPENDS_ON, IMPLEMENTS, PROVIDES_INTERFACE, CONSUMES_INTERFACE, OWNS_DATA,
    TESTED_BY, EDGE_TYPES, DAG_VALID, GENERATION_DEPENDENCY_CYCLE,
    GENERATION_PATH_OWNERSHIP_CONFLICT, GENERATION_FORBIDDEN_DEPENDENCY,
    GENERATION_UNKNOWN_DEPENDENCY, DependencyEdge, DAGValidationResult,
    DependencyDAG, GenerationDependencyDAG, build_dependency_dag,
    validate_dependency_dag, topological_sort_units, ready_set,
)
from .generation_units import (
    INTERFACE_UNIT, SCHEMA_UNIT, IMPLEMENTATION_UNIT, ADAPTER_UNIT,
    API_BOUNDARY_UNIT, TEST_UNIT, CONFIGURATION_UNIT, INTEGRATION_UNIT,
    GENERATION_UNIT_TYPES, PLANNED, BLOCKED, READY, GENERATING, CANDIDATE_READY,
    SYNTAX_REJECTED, CONTRACT_REJECTED, TEST_REJECTED, IMPLEMENTED_UNTESTED,
    UNIT_VERIFIED, INTEGRATION_BLOCKED, FAILED, GENERATION_UNIT_STATUSES,
    NEW_ARTIFACT, EXISTING_MODIFICATION, ARTIFACT_KINDS, GenerationUnit,
    GenerationEvidencePacket, GenerationEvidence, GeneratedArtifactCandidate,
    GeneratedCandidate, ContractValidationResult, GenerationUnitReceipt,
    CodeGenerationProvider, build_generation_evidence_packet,
)
from .generation_checkpoint import (
    CHECKPOINT_READY, CHECKPOINT_STALE, CHECKPOINT_INVALID, GenerationCheckpoint,
    create_generation_checkpoint, validate_generation_checkpoint, resume_completed_units,
)
from .change_impact import (
    CHANGE_PRIVATE, CHANGE_PUBLIC_CONTRACT, CHANGE_SCHEMA, IMPACT_BUDGET_REACHED,
    LARGE_IMPACT_CHANGE, DIRECT_IMPACT, TRANSITIVE_IMPACT, TEST_IMPACT, CONTRACT_IMPACT,
    ChangeImpact, GenerationImpactSet, ChangeIsland, analyze_change_impact, build_change_island,
    detect_contract_drift, detect_interface_drift, compute_change_impact,
    contract_drift, interface_drift,
)
from .project_builder import (
    CORE6_BUILDER_SCHEMA_VERSION, PROVIDER_FAILURE, GENERATION_PROVIDER_FAILURE, SYNTAX_FAILURE,
    CONTRACT_FAILURE, UNIT_TEST_FAILURE, DEPENDENCY_FAILURE, AUTHORITY_FAILURE,
    STALE_EVIDENCE, STALE_PACKET, BUDGET_FAILURE, UNIT_GENERATION_BUDGET_REACHED,
    INTEGRATION_FAILURE, GENERATION_BUDGET_REACHED,
    GENERATION_COMPLETE, GENERATION_PARTIAL, GENERATION_BLOCKED,
    GenerationBudget, ProjectGenerationBudget, ProjectGenerationPlan, GenerationMetrics, GenerationResult,
    GenerationProvider, DeterministicFakeProvider, FakeGenerationProvider,
    units_from_blueprint, build_generation_plan, build_task_generation_plan,
    ProjectBuilder, generate_project, validate_generated_artifact_candidate,
    project_generation_metrics, PROJECT_PLANNED, PROJECT_GENERATING, PROJECT_VERIFIED,
    PROJECT_PROMOTABLE, PROJECT_REQUIRES_FINAL_VERIFICATION,
    benchmark_generation_scenarios,
)
from .core_execution import (
    CORE_INTEGRATION_SCHEMA_VERSION, BUILD, MAINTAIN, DIAGNOSE, REPAIR,
    EXECUTION_MODES, WORKING_SET_FIRST, INITIALIZING, CONTEXT_BUILDING,
    PLANNING, GENERATING, LOCALIZING, EXPERIMENTING, PATCH_SEARCHING,
    CANDIDATE_SELECTED, CANONICAL_APPLYING, VERIFYING, INDEX_UPDATING,
    PROMOTABLE, COMPLETE, BLOCKED, CONTEXT_INSUFFICIENT,
    LOCALIZATION_INSUFFICIENT, DIAGNOSTIC_INCONCLUSIVE, NO_VIABLE_PATCH,
    PATCH_VERIFICATION_FAILED, GENERATION_UNIT_FAILED, AUTHORITY_BLOCKED,
    DNT_BLOCKED, BUDGET_REACHED, FINAL_VERIFICATION_FAILED, PROVIDER_FAILURE,
    STALE_CONTEXT, CoreExecutionBudget, CoreBudget, CoreExecutionState,
    CoreProviderRequest, CoreExecutionResult, new_core_metrics, core_autonomy_lift,
)
from .core_orchestrator import (
    CORE_INTEGRATION_VERSION, GENERATION_PROVIDER, PATCH_PROVIDER,
    SEMANTIC_PROVIDER, PROVIDER_ROLES, CORE_COMPLETE, CORE_PARTIAL, CORE_BLOCKED,
    classify_core_task, ModelPatchCandidateProviderAdapter,
    adapt_candidate_failure_evidence, CoreIntelligenceCoordinator,
    HivoCoreOrchestrator, CoreOrchestrator, execute_core_task,
    inspect_task_context,
)

__all__ = [
    "GEMMA_MODEL", "MemoryStore", "ProjectStore", "SingleModelPolicy",
    "build_execution_stages", "classify_project",
    "ProjectBrainEntity", "TypedReference", "RepositoryMap", "ProjectWorldFact", "ProjectWorldModel",
    "SEMANTIC_COUPLING_SCHEMA_VERSION", "SHARED_CONTRACT", "SHARED_STATE_TRANSITION",
    "SHARED_INVARIANT", "PRODUCER_CONSUMER", "TYPE_SCHEMA_COUPLING",
    "PUBLIC_SURFACE_COUPLING", "ORDER_DEPENDENT", "VERIFICATION_COUPLING",
    "CONFIGURATION_COUPLING", "INDEPENDENT", "GROUP", "MERGE_REQUIRED", "BLOCKED",
    "ANALYSIS_VALIDATED", "ANALYSIS_PARTIAL", "ANALYSIS_CONFLICTING", "AUTHORITY_RANKING",
    "SemanticCoupling", "SemanticWorkGroup", "SemanticCouplingAnalyzer",
    "analyze_semantic_coupling", "refine_semantic_decomposition",
    "verify_semantic_group", "benchmark_semantic_coupling_scenarios",
    "PRE_MUTATION_IMPACT_SCHEMA_VERSION", "DIRECT_IMPLEMENTATION", "PUBLIC_CONTRACT",
    "CALLER_CONSUMER", "TYPE_SCHEMA", "STATE_TRANSITION", "EXPORT_PUBLIC_SURFACE",
    "TEST_BEHAVIOR", "CONFIGURATION", "INVARIANT", "DEPENDENCY", "SIDE_EFFECT",
    "IMPACT_CATEGORIES", "EXPECTED_AND_OBSERVED", "EXPECTED_BUT_MISSING",
    "UNEXPECTED_BUT_RELATED", "UNEXPECTED_AND_OUT_OF_SCOPE", "PRESERVATION_VIOLATED",
    "UNRESOLVED", "CONFLICTING", "IMPACT_ACCEPTED", "IMPACT_INCOMPLETE",
    "IMPACT_CONFLICT", "IMPACT_REQUIRED", "IMPACT_INVALID", "IMPACT_STALE", "IMPACT_VERIFICATION_FAILED",
    "IMPACT_REPLAN_REQUIRED", "IMPACT_PASSED", "IMPACT_FAILED",
    "PreMutationImpactContract", "ImpactContract", "ImpactComparison",
    "MAX_IMPACT_TARGETS", "MAX_IMPACT_OBLIGATIONS", "MAX_IMPACT_PRESERVATIONS",
    "MAX_EXPECTED_RELATION_DELTAS", "MAX_IMPACT_EVIDENCE_ITEMS",
    "MAX_IMPACT_ACTUAL_TARGETS", "MAX_IMPACT_CHANGED_PATHS", "MAX_IMPACT_REVISIONS",
    "MAX_IMPACT_CONTRACT_REVISIONS", "MAX_PRESERVATIONS", "MAX_IMPACT_NEIGHBORHOOD_FACTS",
    "MAX_IMPACT_PROJECTION_CHARS", "build_pre_mutation_impact_contract",
    "create_pre_mutation_impact_contract", "build_impact_contract",
    "validate_pre_mutation_impact_contract", "validate_impact_contract",
    "accept_pre_mutation_impact_contract", "accept_impact_contract",
    "impact_mutation_block_reason", "mutation_authorization_block_reason",
    "capture_actual_mutation_impact", "capture_mutation_impact",
    "evaluate_verification_obligations", "compare_pre_mutation_impact",
    "compare_impact_contract", "verify_pre_mutation_impact",
    "revise_pre_mutation_impact_contract", "revise_impact_contract",
    "project_impact_contract", "impact_contract_projection",
    "benchmark_impact_contract_scenarios", "benchmark_pre_mutation_impact",
    "SATISFIED", "FAILED", "NOT_APPLICABLE",
    "build_repository_map",
    "incremental_reindex", "EvidenceResolutionRequest", "ProjectReferenceResolver",
    "ResolvedEvidence", "create_project_brain_entity", "mark_reference_stale",
    "normalize_legacy_brain_record", "LexicalIndex", "build_lexical_index",
    "incremental_lexical_update", "TaskWorkingSet", "WorkingSetBudget",
    "WorkingSetItem", "build_task_working_set", "expand_working_set",
    "RepoIntelligenceQuery", "SearchCandidate", "RepoIntelligenceResult",
    "RepoIntelligenceBudget", "search_repository", "benchmark_repository_navigation",
    "SearchIntent", "classify_search_intents", "extract_query_signals",
    "DiagnosticBudget", "DiagnosticFailureEvidence", "DiagnosticHypothesis",
    "DiagnosticSession", "seed_hypotheses", "DiagnosticExperiment",
    "ExperimentSelector", "SelectionDecision", "CounterfactualMutationSpec",
    "ExperimentalSandbox", "ProbePermission", "classify_probe_permission",
    "canonical_subject_hash", "subject_tree_snapshot", "BaselineReceipt",
    "DiagnosticResult", "EvidenceItem", "ExperimentReceipt",
    "ExperimentalEvidenceEngine", "ExperimentalEvidenceLedger", "VerificationResult",
    "generate_test_failure_experiments", "generate_error_location_experiments",
    "generate_dependency_stub_experiment", "generate_input_perturbation_experiment",
    "session_from_recovery_failure", "benchmark_diagnostic_scenarios",
    "CoverageEvidence", "CoverageEvidenceProvider", "COVERAGE_AVAILABLE",
    "COVERAGE_NOT_AVAILABLE", "COVERAGE_STALE", "collect_coverage_evidence",
    "ochiai_suspiciousness", "FaultFailureEvidence", "FailureEvidence",
    "LocalizationBudget", "FaultLocalizationBudget", "FaultLocalizationRequest",
    "StackFrame", "StackTraceParser", "FaultCandidate", "FaultLocalizationResult",
    "FaultLocalizationEngine", "parse_stack_trace", "parse_stack_frames",
    "build_fault_localization_request", "localize_fault",
    "seed_hypotheses_from_localization", "rerank_with_experimental_evidence",
    "benchmark_fault_localization_scenarios", "benchmark_fault_localization",
    "TEST_FAILURE", "ASSERTION_FAILURE", "RUNTIME_EXCEPTION", "SYNTAX_FAILURE",
    "VERIFICATION_FAILURE", "ORACLE_FAILURE", "WORKER_EXECUTION_FAILURE",
    "INTEGRATION_FAILURE", "ERROR_LOCATION_SIGNAL", "STACK_TRACE_SIGNAL",
    "FAILING_TEST_SIGNAL", "TEST_DEPENDENCY_SIGNAL", "COVERAGE_SIGNAL",
    "GRAPH_PROXIMITY_SIGNAL", "CHANGE_PROXIMITY_SIGNAL", "LEXICAL_SIGNAL",
    "BRAIN_CONTRACT_SIGNAL", "EXPERIMENTAL_EVIDENCE_SIGNAL", "LOW", "MEDIUM",
    "HIGH", "VERY_HIGH", "DNT_PROTECTED",
    "CORE5_SCHEMA_VERSION", "DIAGNOSTIC_SUSPECT", "FINAL_MUTATION_AUTHORIZED",
    "CORE5_READ_ONLY_SUPPORT", "CORE5_DNT_PROTECTED", "PatchSearchBudget",
    "CandidateSearchBudget", "RepairTargetSet", "RepairEvidencePacket", "RepairProblem",
    "EXACT_VALUE_CHANGE", "CONDITION_CHANGE", "EXPORT_IMPORT_REPAIR",
    "FUNCTION_LOCAL_REWRITE", "SMALL_INSERTION", "SMALL_DELETION", "CALLSITE_ADJUSTMENT",
    "DEPENDENCY_CONFIGURATION_CHANGE", "MULTI_LOCATION_SINGLE_FILE_CHANGE",
    "MULTI_FILE_BOUNDED_CHANGE", "UNKNOWN_STRUCTURAL_CHANGE", "STRATEGY_CLASSES",
    "StrategyDecision", "MutationStrategyRouter", "route_mutation_strategies",
    "DETERMINISTIC_OPERATOR", "REPAIR_TEMPLATE", "EXPERIMENT_DERIVED", "MODEL_PROPOSED",
    "USER_PROPOSED", "PROPOSED", "STALE_BASE", "AUTHORITY_BLOCKED", "SYNTAX_INVALID",
    "TARGET_FAILED", "GUARD_REGRESSION", "CONTRACT_CONFLICT", "V25_5_REJECTED",
    "V25_6_FAILED", "VIABLE", "VERIFIED", "STALE_PATCH_BASE", "REGRESSION_RISK", "SYNTAX_INVALID_CANDIDATE", "PatchOperation", "PatchRepresentation",
    "PatchCandidate", "PatchCandidateReceipt", "CandidateFailureEvidence",
    "ModelPatchCandidateProvider", "generate_deterministic_candidates",
    "generate_experiment_derived_candidate", "normalize_model_candidates", "generate_patch_candidates",
    "PatchSearchResult", "PatchSearchEngine", "search_patch_candidates",
    "apply_selected_patch_candidate", "update_repository_indexes_after_application",
    "benchmark_patch_search_scenarios", "VERIFIED_CANDIDATE", "BEST_VIABLE_CANDIDATE",
    "APPLY_SELECTED_CANDIDATE", "NO_VIABLE_PATCH_CANDIDATE", "PATCH_SEARCH_BUDGET_REACHED",
    "CORE6_BLUEPRINT_SCHEMA_VERSION", "REQUIREMENT_CATEGORIES", "ARCHITECTURE_STYLES",
    "CONTRACT_STATUSES", "ProjectRequirement", "InterfaceSchema", "ProjectInterface",
    "DataSchema", "ContractSchema", "ModuleContract", "ProjectBlueprint",
    "blueprint_identity", "contract_identity", "schema_identity",
    "DEPENDS_ON", "IMPLEMENTS", "PROVIDES_INTERFACE", "CONSUMES_INTERFACE", "OWNS_DATA",
    "TESTED_BY", "EDGE_TYPES", "DAG_VALID", "GENERATION_DEPENDENCY_CYCLE",
    "GENERATION_PATH_OWNERSHIP_CONFLICT", "GENERATION_FORBIDDEN_DEPENDENCY",
    "GENERATION_UNKNOWN_DEPENDENCY", "DependencyEdge", "DAGValidationResult",
    "DependencyDAG", "GenerationDependencyDAG", "build_dependency_dag",
    "validate_dependency_dag", "topological_sort_units", "ready_set",
    "INTERFACE_UNIT", "SCHEMA_UNIT", "IMPLEMENTATION_UNIT", "ADAPTER_UNIT",
    "API_BOUNDARY_UNIT", "TEST_UNIT", "CONFIGURATION_UNIT", "INTEGRATION_UNIT",
    "GENERATION_UNIT_TYPES", "PLANNED", "BLOCKED", "READY", "GENERATING",
    "CANDIDATE_READY", "SYNTAX_REJECTED", "CONTRACT_REJECTED", "TEST_REJECTED",
    "IMPLEMENTED_UNTESTED", "UNIT_VERIFIED", "INTEGRATION_BLOCKED", "FAILED",
    "GENERATION_UNIT_STATUSES", "NEW_ARTIFACT", "EXISTING_MODIFICATION", "ARTIFACT_KINDS",
    "GenerationUnit", "GenerationEvidencePacket", "GenerationEvidence",
    "GeneratedArtifactCandidate", "GeneratedCandidate", "ContractValidationResult",
    "GenerationUnitReceipt", "CodeGenerationProvider", "build_generation_evidence_packet",
    "CHECKPOINT_READY", "CHECKPOINT_STALE", "CHECKPOINT_INVALID", "GenerationCheckpoint",
    "create_generation_checkpoint", "validate_generation_checkpoint", "resume_completed_units",
    "CHANGE_PRIVATE", "CHANGE_PUBLIC_CONTRACT", "CHANGE_SCHEMA", "IMPACT_BUDGET_REACHED",
    "LARGE_IMPACT_CHANGE", "DIRECT_IMPACT", "TRANSITIVE_IMPACT", "TEST_IMPACT", "CONTRACT_IMPACT",
    "ChangeImpact", "GenerationImpactSet", "ChangeIsland", "analyze_change_impact", "compute_change_impact",
    "build_change_island", "detect_contract_drift", "detect_interface_drift",
    "contract_drift", "interface_drift",
    "CORE6_BUILDER_SCHEMA_VERSION", "PROVIDER_FAILURE", "GENERATION_PROVIDER_FAILURE", "SYNTAX_FAILURE", "CONTRACT_FAILURE",
    "UNIT_TEST_FAILURE", "DEPENDENCY_FAILURE", "AUTHORITY_FAILURE", "STALE_EVIDENCE",
    "INTEGRATION_FAILURE", "STALE_PACKET", "BUDGET_FAILURE", "UNIT_GENERATION_BUDGET_REACHED",
    "GENERATION_BUDGET_REACHED", "GENERATION_COMPLETE",
    "GENERATION_PARTIAL", "GENERATION_BLOCKED", "GenerationBudget", "ProjectGenerationPlan",
    "GenerationMetrics", "GenerationResult", "GenerationProvider", "DeterministicFakeProvider",
    "FakeGenerationProvider", "units_from_blueprint", "build_generation_plan", "build_task_generation_plan",
    "ProjectBuilder", "generate_project", "validate_generated_artifact_candidate",
    "project_generation_metrics", "PROJECT_PLANNED", "PROJECT_GENERATING", "PROJECT_VERIFIED",
    "PROJECT_PROMOTABLE", "PROJECT_REQUIRES_FINAL_VERIFICATION", "ProjectGenerationBudget",
    "benchmark_generation_scenarios",
    "CORE_INTEGRATION_SCHEMA_VERSION", "CORE_INTEGRATION_VERSION", "BUILD", "MAINTAIN",
    "DIAGNOSE", "REPAIR", "EXECUTION_MODES", "WORKING_SET_FIRST", "INITIALIZING",
    "CONTEXT_BUILDING", "PLANNING", "GENERATING", "LOCALIZING", "EXPERIMENTING",
    "PATCH_SEARCHING", "CANDIDATE_SELECTED", "CANONICAL_APPLYING", "VERIFYING",
    "INDEX_UPDATING", "PROMOTABLE", "COMPLETE", "BLOCKED", "CONTEXT_INSUFFICIENT",
    "LOCALIZATION_INSUFFICIENT", "DIAGNOSTIC_INCONCLUSIVE", "NO_VIABLE_PATCH",
    "PATCH_VERIFICATION_FAILED", "GENERATION_UNIT_FAILED", "AUTHORITY_BLOCKED",
    "DNT_BLOCKED", "BUDGET_REACHED", "FINAL_VERIFICATION_FAILED", "PROVIDER_FAILURE",
    "STALE_CONTEXT", "CoreExecutionBudget", "CoreBudget", "CoreExecutionState",
    "CoreProviderRequest", "CoreExecutionResult", "new_core_metrics", "core_autonomy_lift",
    "GENERATION_PROVIDER", "PATCH_PROVIDER", "SEMANTIC_PROVIDER", "PROVIDER_ROLES",
    "CORE_COMPLETE", "CORE_PARTIAL", "CORE_BLOCKED", "classify_core_task",
    "ModelPatchCandidateProviderAdapter", "adapt_candidate_failure_evidence",
    "CoreIntelligenceCoordinator", "HivoCoreOrchestrator", "CoreOrchestrator",
    "execute_core_task", "inspect_task_context",
]
